
'use client';

import { useState } from 'react';
import { DashboardSidebar } from '@/components/layout/sidebar';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FileText, Download, Filter, Calendar as CalendarIcon, FileSpreadsheet, Plus, Loader2 } from 'lucide-react';
import { RECENT_REPORTS } from '@/app/lib/mock-data';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import { generateNewReportAction } from '@/app/lib/actions';
import { useToast } from '@/hooks/use-toast';

export default function ReportsPage() {
  const [reports, setReports] = useState(RECENT_REPORTS);
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();

  const handleGenerateReport = async () => {
    setIsGenerating(true);
    const newReport = await generateNewReportAction();
    
    if (newReport) {
      setReports([newReport, ...reports]);
      toast({
        title: "Report Generated",
        description: "Your AI-powered operational summary is ready for review.",
      });
    } else {
      toast({
        variant: "destructive",
        title: "Generation Failed",
        description: "Could not connect to the AI engine. Please try again.",
      });
    }
    setIsGenerating(false);
  };

  const handleDownload = async (report: any) => {
    toast({
      title: "Generating PDF",
      description: `Preparing ${report.name} for local download...`,
    });

    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();
      
      // Title
      doc.setFontSize(22);
      doc.setTextColor(63, 81, 181); // Primary color
      doc.text("MediSight Insights", 20, 20);
      
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text("Operational Performance Report", 20, 30);
      
      // Metadata
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Report ID: ${report.id}`, 20, 45);
      doc.text(`Generated Date: ${report.date}`, 20, 50);
      doc.text(`Report Name: ${report.name}`, 20, 55);
      
      doc.setDrawColor(200, 200, 200);
      doc.line(20, 60, 190, 60);
      
      // Content
      if (report.content) {
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text("Executive Summary", 20, 75);
        
        doc.setFontSize(10);
        doc.setTextColor(60, 60, 60);
        const splitSummary = doc.splitTextToSize(report.content.summary, 170);
        doc.text(splitSummary, 20, 85);
        
        let currentY = 85 + (splitSummary.length * 5) + 15;
        
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text("AI Strategic Recommendations", 20, currentY);
        
        doc.setFontSize(10);
        doc.setTextColor(60, 60, 60);
        currentY += 10;
        
        report.content.recommendations.forEach((rec: string, index: number) => {
          const splitRec = doc.splitTextToSize(`${index + 1}. ${rec}`, 160);
          doc.text(splitRec, 25, currentY);
          currentY += (splitRec.length * 5) + 5;
          
          if (currentY > 270) {
            doc.addPage();
            currentY = 20;
          }
        });
      } else {
        doc.setFontSize(12);
        doc.text("Archived Report Data", 20, 75);
        doc.setFontSize(10);
        doc.text("This is an legacy archived report. Detailed analytics are available in the central management system.", 20, 85);
      }
      
      // Footer
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Confidential - MediSight Mumbai Network - Page ${i} of ${pageCount}`, 20, 285);
      }

      doc.save(`${report.name.replace(/\s+/g, '_')}.pdf`);

      toast({
        title: "Download Successful",
        description: "The report PDF has been saved to your device.",
      });
    } catch (error) {
      console.error('PDF generation failed:', error);
      toast({
        variant: "destructive",
        title: "Download Failed",
        description: "Could not generate the PDF file.",
      });
    }
  };

  return (
    <div className="flex h-screen bg-background overflow-hidden">
      <DashboardSidebar />
      
      <main className="flex-1 overflow-y-auto p-8">
        <header className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-3xl font-headline font-bold text-primary">Automated Reporting</h1>
            <p className="text-muted-foreground">Compliance and performance summaries generated by MediSight AI</p>
          </div>
          <Button 
            onClick={handleGenerateReport} 
            disabled={isGenerating}
            className="gap-2 shadow-lg shadow-primary/20"
          >
            {isGenerating ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Plus className="w-4 h-4" />
            )}
            {isGenerating ? 'Generating AI Summary...' : 'Generate New Report'}
          </Button>
        </header>

        <div className="grid grid-cols-1 xl:grid-cols-4 gap-8">
          <div className="xl:col-span-1 space-y-6">
            <Card className="border-none shadow-md">
              <CardHeader>
                <CardTitle className="text-lg">Filter Reports</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <label className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Report Type</label>
                  <div className="flex flex-wrap gap-2">
                    <Badge variant="outline" className="cursor-pointer hover:bg-primary hover:text-white transition-colors">Operations</Badge>
                    <Badge variant="outline" className="cursor-pointer hover:bg-primary hover:text-white transition-colors">Financial</Badge>
                    <Badge variant="outline" className="cursor-pointer hover:bg-primary hover:text-white transition-colors">Audit</Badge>
                    <Badge variant="outline" className="cursor-pointer hover:bg-primary hover:text-white transition-colors">AI Forecasts</Badge>
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Format</label>
                  <div className="grid grid-cols-2 gap-2">
                    <Button variant="outline" size="sm" className="gap-2">
                      <FileText className="w-3 h-3" /> PDF
                    </Button>
                    <Button variant="outline" size="sm" className="gap-2">
                      <FileSpreadsheet className="w-3 h-3" /> CSV
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>

            <div className="p-6 rounded-2xl bg-primary text-primary-foreground shadow-xl shadow-primary/20">
              <h3 className="font-bold text-lg mb-2">Next Scheduled</h3>
              <p className="text-sm text-primary-foreground/80 mb-4">The Q1 Comprehensive Operational Audit will auto-generate in 12 days.</p>
              <div className="flex items-center gap-2 text-xs font-medium">
                <CalendarIcon className="w-4 h-4" />
                March 31, 2024
              </div>
            </div>
          </div>

          <Card className="xl:col-span-3 border-none shadow-md overflow-hidden">
            <CardHeader className="flex flex-row items-center justify-between bg-card border-b border-border">
              <div>
                <CardTitle>Recent Documents</CardTitle>
                <CardDescription>Archive of generated operations reports</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="p-0">
              <div className="divide-y divide-border">
                {reports.map((report: any) => (
                  <div key={report.id} className="flex items-center justify-between p-6 hover:bg-primary/5 transition-colors group">
                    <div className="flex items-center gap-4">
                      <div className={cn(
                        "w-12 h-12 rounded-xl flex items-center justify-center transition-transform group-hover:scale-110 shadow-sm",
                        report.type === 'PDF' ? "bg-red-100 text-red-600" : "bg-green-100 text-green-600"
                      )}>
                        {report.type === 'PDF' ? <FileText className="w-6 h-6" /> : <FileSpreadsheet className="w-6 h-6" />}
                      </div>
                      <div>
                        <div className="flex items-center gap-2">
                          <h4 className="font-bold text-foreground group-hover:text-primary transition-colors">{report.name}</h4>
                          {report.id.startsWith('rep-') && (
                            <Badge className="bg-blue-100 text-blue-600 hover:bg-blue-100 border-none text-[8px] h-4">AI GENERATED</Badge>
                          )}
                        </div>
                        <div className="flex items-center gap-4 text-xs text-muted-foreground mt-1">
                          <span className="flex items-center gap-1 font-medium">
                            <CalendarIcon className="w-3 h-3" /> {report.date}
                          </span>
                          <span className="font-medium">{report.size}</span>
                          <Badge variant="secondary" className="text-[10px] py-0">{report.type}</Badge>
                        </div>
                      </div>
                    </div>
                    <Button 
                      variant="outline" 
                      size="sm" 
                      onClick={() => handleDownload(report)}
                      className="gap-2 border-primary/20 hover:bg-primary hover:text-white hover:border-primary transition-all shadow-sm"
                    >
                      <Download className="w-4 h-4" />
                      Download PDF
                    </Button>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  );
}
